In [1]:
import numpy as np

Q1.
A class has 4 students and 3 subjects. Their marks are given below. The examiner announces a subject-wise bonus of 5, 2 and 8 marks respectively. Add the bonus to every student in one line using broadcasting, then cap any mark above 100 back to 100 and report how many marks had to be capped.

marks = np.array([[88, 96, 95],
                  [72, 99, 91],
                  [98, 85, 97],
                  [60, 75, 80]])

In [2]:
# Q1

marks = np.array([[88, 96, 95],
                  [72, 99, 91],
                  [98, 85, 97],
                  [60, 75, 80]])

bonus = np.array([5, 2, 8])

marks = marks + bonus

marks = np.minimum(marks, 100)

print(marks)

capped = np.sum(marks == 100)

print("Number of marks capped:", capped)

[[ 93  98 100]
 [ 77 100  99]
 [100  87 100]
 [ 65  77  88]]
Number of marks capped: 4


Q2.
Create a 5x5 matrix with a border of 1s and 0s inside, without writing the matrix out by hand.

In [3]:
# Q2

matrix = np.ones((5, 5), dtype=int)

matrix[1:-1, 1:-1] = 0

print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Q3.
Without running the code, predict the shape of np.arange(30).reshape(5, -1).T. Write your prediction as a comment, then verify it. Also explain in a comment why np.arange(30).reshape(4, -1) fails.

In [4]:
# Q3

# Prediction: reshape(5, -1) gives (5, 6), then .T gives (6, 5)

arr = np.arange(30).reshape(5, -1).T

print(arr)
print("Shape:", arr.shape)

# np.arange(30).reshape(4, -1) fails because
# 30 elements cannot be evenly divided into 4 rows.

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]
Shape: (6, 5)


Q4.
Two arrays of size 4 are given. First join them with hstack and print the shape. Then, using the same two arrays, build a proper (4, 2) two-column table. In a comment, state why the first attempt did not produce two columns.

heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])

In [5]:
# Q4

heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])

first = np.hstack((heights, weights))

print("First attempt:")
print(first)
print("Shape:", first.shape)

table = np.column_stack((heights, weights))

print("\nProper 2-column table:")
print(table)
print("Shape:", table.shape)

# np.hstack joins two 1-D arrays into one longer 1-D array,
# so its shape is (8,), not (4, 2).

First attempt:
[172 158 181 166  68  52  84  59]
Shape: (8,)

Proper 2-column table:
[[172  68]
 [158  52]
 [181  84]
 [166  59]]
Shape: (4, 2)


Q5.
Given a 1D array of 12 monthly sales figures, reshape it into 4 quarters of 3 months each and find which quarter (index) had the highest average sales, along with that average.

sales = np.array([120, 135, 98, 160, 175, 190, 88, 92, 105, 210, 198, 230])

In [6]:
# Q5

sales = np.array([120, 135, 98,
                  160, 175, 190,
                  88, 92, 105,
                  210, 198, 230])

quarters = sales.reshape(4, 3)

print("Quarterly sales:")
print(quarters)

averages = quarters.mean(axis=1)

print("\nQuarter averages:")
print(averages)

highest_quarter = averages.argmax()

print("\nHighest average quarter index:", highest_quarter)
print("Highest average:", averages[highest_quarter])

Quarterly sales:
[[120 135  98]
 [160 175 190]
 [ 88  92 105]
 [210 198 230]]

Quarter averages:
[117.66666667 175.          95.         212.66666667]

Highest average quarter index: 3
Highest average: 212.66666666666666


Q6.
Build a 3x3 multiplication table from the array below using broadcasting only. Do not use loops and do not use np.outer — reshape one of the operands so that broadcasting produces the grid.

a = np.array([2, 3, 4])

In [7]:
# Q6

a = np.array([2, 3, 4])

table = a[:, np.newaxis] * a[np.newaxis, :]

print(table)
print("Shape:", table.shape)

[[ 4  6  8]
 [ 6  9 12]
 [ 8 12 16]]
Shape: (3, 3)
