In [3]:
# create an array of the first 12 odd numbers using a single np.arrange call

import numpy as np 
odd = np.arange(1, 24, 2)
print(odd)


[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [ ]:
#using np.linespace, create 9 equally spaced value from 5 to 45. Before running , predict the gap between consecutive value - then verify 

import numpy as np
values = np.linspace(5, 45, 9)
print(values)
#gap = (45-5)/(9-1) = 40/8 = 5

[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]


In [5]:
#Create np.arange(1, 10) and np.linspace(1, 9, 9). Print both arrays and compare their dtype. Why are they different?

x = np.arange(1, 10)
y = np.linspace(1, 9, 9)
print(x)
print(y)
print(x.dtype)
print(y.dtype)

[1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
int64
float64


In [6]:
#Create a 6×6 identity matrix with integer dtype. The output must show no decimal points.

np.eye(6, dtype=int)
print(np.eye(6, dtype=int))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [7]:
#Create a 3×4 matrix where every element is 5, and report its shape, size, and ndim.

x = np.full((3, 4), 5)
print(x)
print("Shape:", x.shape)
print("Size:", x.size)
print("Number of dimensions:", x.ndim)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Shape: (3, 4)
Size: 12
Number of dimensions: 2


In [10]:
#Given a = np.array([2, 4, 6]) and b = np.array([2.0, 4.0, 6.0]), check both arrays' dtype. Then convert b to integer dtype using astype(), and verify the dtype after conversion.


a= np.array([2, 4, 6])
b= np.array([2.0, 4.0, 6.0])
print("a dtype:", a.dtype)
print("b dtype:", b.dtype)
b_int = b.astype(int)
print("b converted to int dtype:", b_int.dtype)

a dtype: int64
b dtype: float64
b converted to int dtype: int64


In [ ]:
#Predict the exact output of np.array([10.9, 25.5, 39.99]).astype(int) before running it. What rule does the result prove?

x = np.array([10.9, 25.5, 39.99]).astype(int)
print(x)


[10 25 39]


In [12]:
#Given arr = np.arange(10, 101, 10) - extract: (a) the 4th element, (b) the last element using negative indexing, (c) the 2nd-last element.

x = np.arange(10, 101, 10)
print("4th element:", x[3])
print("Last element:", x[-1])
print("2nd-last element:", x[-2])

4th element: 40
Last element: 100
2nd-last element: 90


In [13]:
#From the same arr, slice out exactly [30 40 50 60], and separately produce the full array in reverse.

print("Sliced array:", x[2:6])
print("Reversed array:", x[::-1])


Sliced array: [30 40 50 60]
Reversed array: [100  90  80  70  60  50  40  30  20  10]
