In [2]:
import numpy as np

x = np.array([1,4,4,3,9,4,8])
print(x)
print(x.astype('int32'))
print(x)

[1 4 4 3 9 4 8]
[1 4 4 3 9 4 8]
[1 4 4 3 9 4 8]


In [3]:
x = np.arange(10)
y = np.arange(11,21)
print(x)
print(y)
print(x+y)

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19 20]
[11 13 15 17 19 21 23 25 27 29]


In [4]:
x = np.arange(6).reshape(2,3)
y = np.arange(3).reshape(1,3)
print(x)
print(y)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]


In [5]:
#np.random.seed() + np.random.rand()

np.random.rand(5)

array([0.76052397, 0.9475427 , 0.48739668, 0.47467039, 0.42989448])

In [6]:
#Set seed = 42 and simulates 10 dice rolls ( values 1 - 6) using randit.

x = np.random.seed(42)
dice_rolls = np.random.randint(1, 7, size=10)
print(dice_rolls)

[4 5 3 5 5 2 3 3 3 5]


In [7]:
arr = np.arange(10)
print(arr.shape)
arr1 = arr.reshape(1,-1)
print("Row Vector :", arr1)
arr2 = arr.reshape(-1,1)
print("Column Vector :", arr2)

(10,)
Row Vector : [[0 1 2 3 4 5 6 7 8 9]]
Column Vector : [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [8]:
import numpy as np

U = np.ones((3,4))
result = U + np.array([[10],[20],[30]])

print(result)

[[11. 11. 11. 11.]
 [21. 21. 21. 21.]
 [31. 31. 31. 31.]]


In [9]:
A = np.ones((3,4))
B = np.array([1,2,3,4])

print(A+B)

[[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]


In [12]:
A = np.array([[1],[2],[3]])
B = np.array([[10,20,30,40,50]])

print(A+B)

[[11 21 31 41 51]
 [12 22 32 42 52]
 [13 23 33 43 53]]


In [13]:
import numpy as np

table = np.arange(1,11).reshape(10,1) * np.arange(1,11)

print(table)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [14]:
import numpy as np

arr = np.arange(1,7).reshape(2,3)

f = arr.flatten()
r = arr.ravel()

f[0] = 100
r[0] = 500

print(arr)
print(f)
print(r)

[[500   2   3]
 [  4   5   6]]
[100   2   3   4   5   6]
[500   2   3   4   5   6]


In [3]:
import numpy as np
marks = np.array([35, 69, 75, 44, 32, 90 ])
print(np.where(marks > 50, "Pass", "Fail"))

['Fail' 'Pass' 'Pass' 'Fail' 'Fail' 'Pass']


In [6]:
# NESTED np.Where
marks = np.array([35, 69, 75, 44, 32, 90 ])
print(grades := np.where(marks > 80, "A", np.where(marks > 60, "B", np.where(marks > 40, "C", "D"))))
print(marks)

['D' 'B' 'B' 'C' 'D' 'A']
[35 69 75 44 32 90]


In [8]:
#1. Build one tahi from
#s1,s2  and s3.
#2. Front tat table, print the number of students and the number of subjects as two separate numbers.
#3. Print the total count of marks entries stored in the table.
#4. Store the same table as decimals instead of whole numbers.
#5. Convert old into a form where arithmetic works, then print the total marks of both students.
#6. Attach old below the main table so that all five students sit in one table.

import numpy as np
s1 = np.array([35, 69, 75])
s2 = np.array([44, 32, 90])
s3 = np.array([50, 60, 70]) 
print(table := np.array((s1,s2,s3)))
print("Number of Students :", table.shape[0])
print("Number of Subjects :", table.shape[1])
print("Total Count of Marks Entries :", table.size)



[[35 69 75]
 [44 32 90]
 [50 60 70]]
Number of Students : 3
Number of Subjects : 3
Total Count of Marks Entries : 9


In [10]:
#Q2. Templates and sequences
#Tasks

#Create a blank mark sheet for 6 students and 4 subjects, every entry starting at 0.
#Create a table of the same size where every student is temporarily given 35.
#A batch has roll numbers running from 101 to 130. Generate only the alternate roll numbers, and print how many were generated.
#Split a 3-hour practical into 7 equally spaced time markers, including both the start and the end.
#Create a 5 × 5 table that has 10 on the diagonal and 0 everywhere else.
#Create a 4 × 4 table that has 100 on the diagonal and 35 everywhere else.

students = np.zeros((6,4))
print(students)
marks = np.full((6,4), 35)
print(marks)
roll_numbers = np.arange(101, 131, 2)
print(roll_numbers)
equal_time_markers = np.linspace(0, 3, 7)
print(equal_time_markers)
table1 = np.eye(5) * 10
print(table1)   
table2 = np.full((4,4), 35)
print(table2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]]
[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
[0.  0.5 1.  1.5 2.  2.5 3. ]
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]
[[35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]]


###

In [13]:
#Q3. The attendance row
#Tasks

#Print the first and the last student's attendance without writing the class strength anywhere in your code.
#Print the attendance of every alternate student, starting from the second one.
#Print the last four values.
#Reverse the row, then print every third value of the reversed row.
#Change the attendance of the two middle students to 30 each.
#Compare the first half of the row with the second half position by position, and print the difference.
#Print the top three values of the row after reversing it.

print(attendance := np.array([22, 18, 25, 12, 20, 24, 9, 21, 17, 23]))
print(attendance[[0, -1]])
print(attendance[1::2])
print(attendance[-4:])
reverse_attendance = attendance[::-1]
print(reverse_attendance[::3])
reverse_attendance[3:5] = 30
print(reverse_attendance)
print(reverse_attendance[:5] - reverse_attendance[5:])
print(np.sort(reverse_attendance)[-3:][::-1])

[22 18 25 12 20 24  9 21 17 23]
[22 23]
[18 12 24 21 23]
[ 9 21 17 23]
[23  9 12 22]
[23 17 21 30 30 20 12 25 18 22]
[ 3  5 -4 12  8]
[30 30 25]


In [2]:
#Q4. Reading the mark sheet
#The columns are Math, Physics, Chemistry and English.

#Tasks

#Print the Physics and Chemistry marks of the middle three students only.
#Print the last subject's marks for the whole class.
#Produce a table containing only the first and the last subject of every student.
#Print the mark sheet with the students in reverse order.
#Increase only the Chemistry marks of the whole class by 5, leaving the rest unchanged.
#Print the mark that sits in the last row and the second-last column.
#Produce a table of the last two students and their first two subjects.

import numpy as np

maths = np.array([35, 69, 75, 44, 32, 90])
physics = np.array([40, 70, 80, 50, 30, 95])
chemistry = np.array([45, 65, 85, 55, 35, 100])
english = np.array([50, 60, 70, 40, 30, 90])



In [ ]:
# Q5. Scholarship shortlisting
# Tasks

# Print the totals of students who scored above 250.
# Print the totals of students scoring above 180 but below 250.
# Print the totals of students who scored either below 150 or above 380.
# Print how many students fall in the band of task 2.
# Print the average of only those students who scored above 200.
# Print the index position of every student below 150.
# Print the highest total among the students who did not make the merit band of task 1.

import numpy as np
marks = np.array([[35, 40, 45, 50],
                  [69, 70, 65, 60],
                  [75, 80, 85, 70],
                  [44, 50, 55, 40],
                  [32, 30, 35, 30],
                  [90, 95, 100, 90]])
print(totals := np.sum(marks, axis=1))
print(totals[totals > 250])
print(totals[(totals > 180) & (totals < 250)])
print(totals[(totals < 150) | (totals > 380)])
print(np.sum((totals > 180) & (totals < 250)))
print(np.mean(totals[totals > 200]))
print(np.where(totals < 150)[0])
print(np.max(totals[totals <= 250]))


[170 264 310 189 127 375]
[264 310 375]
[189]
[127]
1
316.3333333333333
[4]
189


In [4]:
# Q6. After revaluation
# Tasks

# Increase every student's marks by 15% and round to 2 decimals.
# After the increase, no student may show more than 100. Produce the corrected list.
# Print how many students gained less than 10 marks from this increase.
# The pass mark is 40. Print how many students were failing before the increase and how many after.
# Print each student's marks as a percentage of the topper's marks, rounded to 1 decimal.
# Print the total number of marks the school gave away in this revaluation.

import numpy as np
marks = np.array([[35, 40, 45, 50],
                  [69, 70, 65, 60],
                  [75, 80, 85, 70],
                  [44, 50, 55, 40],
                  [32, 30, 35, 30],
                  [90, 95, 100, 90]])
increased_marks = np.round(marks * 1.15, 2)
corrected_marks = np.clip(increased_marks, 0, 100)
print("Increased Marks:\n", increased_marks)
print("Corrected Marks:\n", corrected_marks)
gains = corrected_marks - marks
print("Number of students who gained less than 10 marks:", np.sum(np.sum(gains, axis=1) < 10))
print("Number of students failing before increase:", np.sum(np.sum(marks < 40, axis=1) > 0))
print("Number of students failing after increase:", np.sum(np.sum(corrected_marks < 40, axis=1) > 0))
topper_marks = np.max(np.sum(corrected_marks, axis=1))
percentages = np.round((np.sum(corrected_marks, axis=1) / topper_marks) * 100, 1)
print("Percentages of each student relative to topper's marks:\n", percentages)
total_marks_given_away = np.sum(corrected_marks) - np.sum(marks)
print("Total marks given away in revaluation:", total_marks_given_away) 

Increased Marks:
 [[ 40.25  46.    51.75  57.5 ]
 [ 79.35  80.5   74.75  69.  ]
 [ 86.25  92.    97.75  80.5 ]
 [ 50.6   57.5   63.25  46.  ]
 [ 36.8   34.5   40.25  34.5 ]
 [103.5  109.25 115.   103.5 ]]
Corrected Marks:
 [[ 40.25  46.    51.75  57.5 ]
 [ 79.35  80.5   74.75  69.  ]
 [ 86.25  92.    97.75  80.5 ]
 [ 50.6   57.5   63.25  46.  ]
 [ 36.8   34.5   40.25  34.5 ]
 [100.   100.   100.   100.  ]]
Number of students who gained less than 10 marks: 0
Number of students failing before increase: 2
Number of students failing after increase: 1
Percentages of each student relative to topper's marks:
 [ 48.9  75.9  89.1  54.3  36.5 100. ]
Total marks given away in revaluation: 184.0


In [6]:
# Q7. The result summary
# Tasks

# Print the class average and the middle value of the class.
# Print the gap between the highest and the lowest marks.
# Print the index positions of the topper and of the weakest student.
# Print the second highest marks in the class.
# Print how many students scored above the class average.
# Print how many students lie within one standard deviation of the class average.
# Print the class average after removing the topper.

import numpy as np
marks = np.array([[35, 40, 45, 50],
                  [69, 70, 65, 60],
                  [75, 80, 85, 70],    
                  [44, 50, 55, 40],
                  [32, 30, 35, 30],
                  [90, 95, 100, 90]])
totals = np.sum(marks, axis=1)
class_average = np.mean(totals)
middle_value = np.median(totals)
gap = np.max(totals) - np.min(totals)
topper_index = np.argmax(totals)
weakest_index = np.argmin(totals)
second_highest = np.partition(totals, -2)[-2]
above_average_count = np.sum(totals > class_average)
std_dev = np.std(totals)
within_one_std_dev_count = np.sum((totals >= (class_average - std_dev)) & (totals <= (class_average + std_dev)))
average_without_topper = np.mean(np.delete(totals, topper_index))
print("Class Average:", class_average)
print("Middle Value:", middle_value)
print("Gap between highest and lowest marks:", gap)
print("Index of Topper:", topper_index)
print("Index of Weakest Student:", weakest_index)
print("Second Highest Marks:", second_highest)
print("Number of students above class average:", above_average_count)
print("Number of students within one standard deviation of class average:", within_one_std_dev_count)
print("Class Average after removing topper:", average_without_topper)   

Class Average: 239.16666666666666
Middle Value: 226.5
Gap between highest and lowest marks: 248
Index of Topper: 5
Index of Weakest Student: 4
Second Highest Marks: 310
Number of students above class average: 3
Number of students within one standard deviation of class average: 4
Class Average after removing topper: 212.0


In [7]:
# Q8. Subject-wise and student-wise reports
# Tasks

# Print the average of each subject and the total of each student.
# Print the index of the toughest subject for the class.
# Print the index of the student who topped overall.
# For every subject, print the marks of the student who topped that subject.
# Print how many students scored above 60 in each subject.
# Print the index of the subject in which the class marks are the most spread out.
# Print the total marks of the student who scored the lowest in Chemistry.

import numpy as np
marks = np.array([[35, 40, 45, 50],
                  [69, 70, 65, 60],
                  [75, 80, 85, 70],
                    [44, 50, 55, 40],
                    [32, 30, 35, 30],
                    [90, 95, 100, 90]])
subject_averages = np.mean(marks, axis=0)
toughest_subject_index = np.argmin(subject_averages)
student_totals = np.sum(marks, axis=1)
topper_index = np.argmax(student_totals)
topper_per_subject = np.max(marks, axis=0)
above_60_counts = np.sum(marks > 60, axis=0)
subject_spread = np.ptp(marks, axis=0)
most_spread_subject_index = np.argmax(subject_spread)
lowest_chemistry_index = np.argmin(marks[:, 2])
lowest_chemistry_total = student_totals[lowest_chemistry_index]
print("Subject Averages:", subject_averages)
print("Toughest Subject Index:", toughest_subject_index)
print("Topper Index:", topper_index)
print("Topper Marks per Subject:", topper_per_subject)
print("Number of Students above 60 in each subject:", above_60_counts)
print("Subject with most spread out marks Index:", most_spread_subject_index)
print("Total Marks of Student with Lowest Chemistry Score:", lowest_chemistry_total)    



Subject Averages: [57.5        60.83333333 64.16666667 56.66666667]
Toughest Subject Index: 3
Topper Index: 5
Topper Marks per Subject: [ 90  95 100  90]
Number of Students above 60 in each subject: [3 3 3 2]
Subject with most spread out marks Index: 1
Total Marks of Student with Lowest Chemistry Score: 127


In [8]:
# Q10. Grace marks and weightage
# Tasks

# Apply the subject-wise grace marks to the whole class, keeping every value at or below 100.
# Multiply each subject by its own weightage and print the table rounded to 1 decimal.
# Produce a table showing how far each mark sits from that subject's own class average.
# Give 5 bonus marks to the first student, 0 to the second, 2 to the third and 0 to the fourth — in a single operation.
# From the table of task 3, print how many entries lie below the subject average.
# Produce a table where every subject is brought to one scale by subtracting its average and dividing by its spread. Round to 2 decimals.

import numpy as np
marks = np.array([[35, 40, 45, 50],
                  [69, 70, 65, 60],
                  [75, 80, 85, 70],
                  [44, 50, 55, 40],
                  [32, 30, 35, 30],
                  [90, 95, 100, 90]])
grace_marks = np.array([5, 10, 15, 20])
marks_with_grace = np.clip(marks + grace_marks, 0, 100)
weightage = np.array([0.2, 0.3, 0.4, 0.1])
weighted_marks = np.round(marks_with_grace * weightage, 1)
subject_averages = np.mean(marks_with_grace, axis=0)
deviation_from_average = marks_with_grace - subject_averages
bonus_marks = np.array([5, 0, 2, 0])    
marks_with_bonus = marks_with_grace + bonus_marks
total_below_average = np.sum(marks_with_bonus < subject_averages)
spread = np.ptp(marks_with_grace, axis=0)
scaled_marks = np.round((marks_with_grace - subject_averages) / spread, 2)
print("Marks with Grace:\n", marks_with_grace)
print("Weighted Marks:\n", weighted_marks)
print("Deviation from Subject Averages:\n", deviation_from_average)
print("Marks with Bonus:\n", marks_with_bonus)
print("Number of Entries Below Subject Average:", total_below_average)
print("Scaled Marks:\n", scaled_marks)
print("Subject Averages:", subject_averages)

Marks with Grace:
 [[ 40  50  60  70]
 [ 74  80  80  80]
 [ 80  90 100  90]
 [ 49  60  70  60]
 [ 37  40  50  50]
 [ 95 100 100 100]]
Weighted Marks:
 [[ 8.  15.  24.   7. ]
 [14.8 24.  32.   8. ]
 [16.  27.  40.   9. ]
 [ 9.8 18.  28.   6. ]
 [ 7.4 12.  20.   5. ]
 [19.  30.  40.  10. ]]
Deviation from Subject Averages:
 [[-22.5        -20.         -16.66666667  -5.        ]
 [ 11.5         10.           3.33333333   5.        ]
 [ 17.5         20.          23.33333333  15.        ]
 [-13.5        -10.          -6.66666667 -15.        ]
 [-25.5        -30.         -26.66666667 -25.        ]
 [ 32.5         30.          23.33333333  25.        ]]
Marks with Bonus:
 [[ 45  50  62  70]
 [ 79  80  82  80]
 [ 85  90 102  90]
 [ 54  60  72  60]
 [ 42  40  52  50]
 [100 100 102 100]]
Number of Entries Below Subject Average: 12
Scaled Marks:
 [[-0.39 -0.33 -0.33 -0.1 ]
 [ 0.2   0.17  0.07  0.1 ]
 [ 0.3   0.33  0.47  0.3 ]
 [-0.23 -0.17 -0.13 -0.3 ]
 [-0.44 -0.5  -0.53 -0.5 ]
 [ 0.56  0.5   0.