In [1]:
! pip3 install numpy

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a Python library that isn't in Homebrew,
    use a virtual environment:
    
    python3 -m venv path/to/venv
    source path/to/venv/bin/activate
    python3 -m pip install xyz
    
    If you wish to install a Python application that isn't in Homebrew,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. You can install pipx with
    
    brew install pipx
    
    You may restore the old behavior of pip by passing
    the '--break-system-packages' flag to pip, or by adding
    'break-system-packages = true' to your pip.conf file. The latter
    will permanently disable this error.
    
    If you disable this error, we STRONGLY recommend that you additionally
    pass the '--user' flag to pip, or set 

In [1]:
import numpy as np

In [3]:
x=np.array([2,3,5,6,7])
print(x)
print(type(x))

[2 3 5 6 7]
<class 'numpy.ndarray'>


In [14]:
print(np.ones(10))
print(np.ones([3,4]))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
print(np.full((4,3),15))

[[15 15 15]
 [15 15 15]
 [15 15 15]
 [15 15 15]]


In [17]:
arr = np.arange(20).reshape(5,4)
print(arr)
print(arr[1:4, 1:3])  # Slicing rows 1 to 3 and columns 1 to 2
print(arr[1,1:]) # Slicing row 1 and columns 1 to end

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 5  6]
 [ 9 10]
 [13 14]]
[5 6 7]


In [21]:
arr = np.arange(20).reshape(5,4)
#print(arr)
print(arr[1:3, 2::-1])  # Slicing rows 1 to 3 and columns 1 to 2
#print(arr[1,-1:]) # Slicing row 1 and columns 1 to end

[[ 6  5  4]
 [10  9  8]]
